services:
  - type: web
    name: portfolio-frontend
    env: node
    nodeVersion: "20.11.0"
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://portfolio-api.onrender.com
